#
# Originally from:
#   https://github.com/neurokernel/scikit-cuda_conda_recipe
#

{%set build = 0 %}
{%set version = '0.5.1' %}

{% set cuda_version = "8.0" %}

package:
  name: scikit-cuda
  version: {{version}}

about:
  home: http://github.com/lebedov/scikit-cuda
  license: BSD License
  summary: "Python interface to GPU-powered libraries."

source:
  fn: scikit-cuda-{{version}}.tar.gz
  url: https://pypi.python.org/packages/source/s/scikit-cuda/scikit-cuda-{{version}}.tar.gz
  md5: 85799293d64886501e84c7b41a808fe2

requirements:
  build:
    - python
    - setuptools
    - numpy
    - mako

    # pycuda
    - cuda-feature {{ cuda_version }}  # this won't be needed when conda packages tracking 2+ features work
    - cuda-dev-feature {{ cuda_version }}
    - pycuda

  run:
    - python
    - numpy
    - mako
    - pycuda

    # account for scikit-cuda weirdnesses
    - setuptools  # yes, this is needed too at runtime
    - pytest      # yes, this is needed too at runtime

build:
  number: {{build}}
  string: py{{py}}_{{build}}
  script:
    - python setup.py install --single-version-externally-managed --record record.txt

test:
  source_files:
    - tests
  requires:
    - pytest
    - scipy
    - cuda-feature {{ cuda_version }}  # this won't be needed when conda packages tracking 2+ features work
    - cuda-dev-feature {{ cuda_version }}
  imports:
    - skcuda
    # need something more challenging
  commands:
    # Again, nastily commented because we are hitting this issue:
    #   https://github.com/lebedov/scikit-cuda/issues/171
    # Revisit and reenable when time allows
    # (these are parts of the libs unused by neon so do not affect us really)
    # - py.test tests

extra:
  recipe-url: https://github.com/loopbio/scikit-cuda-feedstock
  recipe-maintainers:
    - sdvillal
