channels:
  sources:
    - loopbio
    - conda-forge
    - defaults
  targets:
    - [loopbio, main]

github:
  user_or_org: 'loopbio'

docker:
  image: sdvillal/linux-anvil-cudnn
  executable: nvidia-docker
  # See https://github.com/conda-forge/conda-smithy/pull/463
  # Options are:
  #   - disable cuda-based tests in build.sh
  #     (needed anyway if building, e.g., in circleci)
  #   - use nvidia-docker and let all the tests run
  #     I prefer this last option, if only because of peace of mind
  #     we are building anyway in our GPU-equipped machines ATM
